/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class principal extends javax.swing.JFrame {
    public static String lastcontent;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        //this.resize(700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttcargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblarchivosel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoSel = new javax.swing.JTextArea();
        bsalir = new javax.swing.JButton();
        statusbar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttcargar.setText("Cargar");
        bttcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcargarActionPerformed(evt);
            }
        });
        jPanel1.add(bttcargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Archivo seleccionado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));

        lblarchivosel.setBackground(new java.awt.Color(255, 255, 255));
        lblarchivosel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblarchivosel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 400, 20));

        TextoSel.setEditable(false);
        TextoSel.setBackground(new java.awt.Color(255, 255, 255));
        TextoSel.setColumns(20);
        TextoSel.setRows(5);
        jScrollPane1.setViewportView(TextoSel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 280));

        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 60, -1));

        statusbar.setBackground(new java.awt.Color(102, 102, 102));
        statusbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(statusbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 700, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ANÁLISIS DE REDES SOCIALES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        btnsave.setText("Guardar");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        System.exit(0);
    }                                      

    private void bttcargarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //dlgarchivosel f = new dlgarchivosel (this, true);
        //f.setVisible(true);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter txtonly = new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.setFileFilter(txtonly);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = jfc.getSelectedFile();
            lblarchivosel.setText(selectedFile.getAbsolutePath());
            lastcontent = Grafo.ReadContent(selectedFile);
            TextoSel.setText(lastcontent);
            JOptionPane.showMessageDialog(null, "Recuerde guardar para mantener los cambios en la memoria", "RECORDATORIO",JOptionPane.INFORMATION_MESSAGE);
            btnsave.setEnabled(true);
            ///Boolean val = Grafo.WriteContent(lastcontent, Grafo.appfile);
            
	}
    }                                         

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Boolean val = Grafo.WriteContent(lastcontent, Grafo.appfile);
        if (val == true){
            JOptionPane.showMessageDialog(null, "Se ha guardado el contenido satisfactoriamente", "GUARDADO",JOptionPane.INFORMATION_MESSAGE);
            btnsave.setEnabled(false);
        }
        else
        { 
          JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "ERROR",JOptionPane.ERROR_MESSAGE);  
        }

    }                                       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
    }

    // Variables declaration - do not modify                     
    public javax.swing.JTextArea TextoSel;
    private javax.swing.JButton bsalir;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton bttcargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblarchivosel;
    private javax.swing.JLabel statusbar;
    // End of variables declaration                   
}
