/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlgdelrel extends javax.swing.JDialog {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgrel.class.getName());

    /**
     * Creates new form dlgrel
     */
    public dlgdelrel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btacept = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        delrel = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Agregar nuevo usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(442, 188));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(442, 188));
        jPanel1.setMinimumSize(new java.awt.Dimension(442, 188));
        jPanel1.setPreferredSize(new java.awt.Dimension(442, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Eliminar relación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Seleccion la relación a eliminar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btacept.setText("Aceptar");
        btacept.setMaximumSize(new java.awt.Dimension(76, 29));
        btacept.setMinimumSize(new java.awt.Dimension(76, 29));
        btacept.setPreferredSize(new java.awt.Dimension(76, 29));
        btacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaceptActionPerformed(evt);
            }
        });
        jPanel1.add(btacept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 90, 30));

        btcancel.setText("Cancelar");
        btcancel.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 90, 30));

        delrel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(delrel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaceptActionPerformed
        // TODO add your handling code here:
        String selrel = this.delrel.getSelectedItem().toString();
        if (selrel.equals("--Seleccionar--"))
        {   
            JOptionPane.showMessageDialog(null, "Debe seleccionar la relación a eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else  
        {
            int result = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el usuario "+selrel+"?", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION)
            {
                Inicio.objRels.delrelation(selrel);
                JOptionPane.showMessageDialog(null, "Se ha eliminado la relación correctamente.", "ELIMINADO", JOptionPane.INFORMATION_MESSAGE);
                String newtext = Inicio.refreshRels();
                Inicio.f.txtrel.setText(newtext);
                this.dispose();
                Inicio.recordatorio();
                
            }
        }
    }//GEN-LAST:event_btaceptActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgrel dialog = new dlgrel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void filldelRel()
    {
        this.delrel.removeAllItems();
        this.delrel.addItem("--Seleccionar--");
        for(int i=0; i<Inicio.objRels.relations.length; i++)
        {
            this.delrel.addItem(Inicio.objRels.relations[i][0] + ", " + Inicio.objRels.relations[i][1]);
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacept;
    private javax.swing.JButton btcancel;
    public javax.swing.JComboBox<String> delrel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
