/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class dlgrel extends javax.swing.JDialog {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgrel.class.getName());

    /**
     * Creates new form dlgrel
     */
    public dlgrel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btacept = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        user1s = new javax.swing.JComboBox<>();
        user2s = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Agregar nuevo usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(494, 250));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(494, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(494, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(494, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Agregar nueva relación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione otro usuario existente relacionado:  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("unilateral de su parte:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nota:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("No puedes agregar una relación con el mismo usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btacept.setText("Aceptar");
        btacept.setMaximumSize(new java.awt.Dimension(76, 29));
        btacept.setMinimumSize(new java.awt.Dimension(76, 29));
        btacept.setPreferredSize(new java.awt.Dimension(76, 29));
        btacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaceptActionPerformed(evt);
            }
        });
        jPanel1.add(btacept, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, 30));

        btcancel.setText("Cancelar");
        btcancel.setMaximumSize(new java.awt.Dimension(76, 29));
        btcancel.setMinimumSize(new java.awt.Dimension(76, 29));
        btcancel.setPreferredSize(new java.awt.Dimension(76, 29));
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 90, 30));

        user1s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(user1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        user2s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        user2s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2sActionPerformed(evt);
            }
        });
        jPanel1.add(user2s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Seleccione un usuario existente con el que se establecerá una relación");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaceptActionPerformed
        // TODO add your handling code here:
        String user1 = this.user1s.getSelectedItem().toString();
        String user2 = this.user2s.getSelectedItem().toString();
        if (user1.equals("--Seleccionar--")||user2.equals("--Seleccionar--"))
        {   
            JOptionPane.showMessageDialog(null, "Debe seleccionar tanto el usuario como su relación.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else  
        {
            if (user1.equals(user2))
            {
                JOptionPane.showMessageDialog(null, "No se puede establecer una relación de un usario con él mismo.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else
            {    
                if (Inicio.objRels.relexist(user1, user2) == true)
                {
                    JOptionPane.showMessageDialog(null, "No puede agregar una relación que ya existe", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    Inicio.objRels.addrelations(user1, user2);
                    JOptionPane.showMessageDialog(null, "Se ha agregado la relación satisfactoriamente", "AGREGADO", JOptionPane.INFORMATION_MESSAGE);
                    String result = Inicio.refreshRels();
                    Inicio.princ.txtrel.setText(result);
                    this.dispose();
                    Inicio.recordatorio();
                }
            }
        }
    }//GEN-LAST:event_btaceptActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void user2sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user2sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgrel dialog = new dlgrel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void fillUser1()
    {   /**
        * Elimina todos los items de la lista de selección 1 o ComboBox(users1s)
        * Agrega un item a la lista de selección 1(users1s) llamado "--Seleccionar--" que indica que es estrictamente necesario seleccionar un usuario
        * Modifica la lista de selección 1(users1s)  para que solo estén los usuarios del arreglo users
        * Itera sobre todos los usuarios (nodos) del arreglo users y los agrega a la lista de selección 1(users1s)
        */
        this.user1s.removeAllItems();
        this.user1s.addItem("--Seleccionar--");
        for(int i=0; i<Inicio.objUsers.users.length; i++)
        {
            this.user1s.addItem(Inicio.objUsers.users[i]);
        }
    }
    
    public void fillUser2()
    {
         /**
        * Elimina todos los items de la lista de selección 2 o ComboBox(users2s)
        * Agrega un item a la lista de selección 2(users2s) llamado "--Seleccionar--" que indica que es estrictamente necesario seleccionar un usuario
        * Modifica la lista de selección 2(users2s)  para que solo estén los usuarios del arreglo users
        * Itera sobre todos los usuarios (nodos) del arreglo users y los agrega a la lista de selección 2(users2s)
        */
        this.user2s.removeAllItems();
        this.user2s.addItem("--Seleccionar--");
        for(int i=0; i<Inicio.objUsers.users.length; i++)
        {
            this.user2s.addItem(Inicio.objUsers.users[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacept;
    private javax.swing.JButton btcancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> user1s;
    public javax.swing.JComboBox<String> user2s;
    // End of variables declaration//GEN-END:variables
}
