/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 * Importa las librerías
*/
import static interfaz.Inicio.getRelationships;
import static interfaz.Inicio.getUsers;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JOptionPane;


/**
 *
 * @author Daniela
 */
public class principal extends javax.swing.JFrame {
    public static String lastcontent;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        //this.resize(700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttcargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblarchivosel = new javax.swing.JLabel();
        bsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        adduser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtusr = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtrel = new javax.swing.JTextArea();
        addrel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttcargar.setText("Cargar");
        bttcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcargarActionPerformed(evt);
            }
        });
        jPanel1.add(bttcargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Archivo seleccionado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 20));

        lblarchivosel.setBackground(new java.awt.Color(255, 255, 255));
        lblarchivosel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblarchivosel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 400, 20));

        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ANÁLISIS DE REDES SOCIALES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        btnsave.setText("Guardar");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 80, 30));

        adduser.setText("Agregar usuario");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });
        jPanel1.add(adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jButton2.setText("Eliminar usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        txtusr.setEditable(false);
        txtusr.setBackground(new java.awt.Color(255, 255, 255));
        txtusr.setColumns(20);
        txtusr.setRows(5);
        jScrollPane3.setViewportView(txtusr);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 380, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Relaciones");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Usuarios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtrel.setEditable(false);
        txtrel.setBackground(new java.awt.Color(255, 255, 255));
        txtrel.setColumns(20);
        txtrel.setRows(5);
        jScrollPane4.setViewportView(txtrel);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 380, 160));

        addrel.setText("Agregar relacción");
        addrel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrelActionPerformed(evt);
            }
        });
        jPanel1.add(addrel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bsalirActionPerformed

    private void bttcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcargarActionPerformed
        // TODO add your handling code here:
        //dlgarchivosel f = new dlgarchivosel (this, true);
        //f.setVisible(true);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter txtonly = new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.setFileFilter(txtonly);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = jfc.getSelectedFile();
            lblarchivosel.setText(selectedFile.getAbsolutePath());
            lastcontent = Inicio.ReadContent(selectedFile);
            Inicio.getUsers(lastcontent);
            Inicio.getRelationships(lastcontent);
            String result = Inicio.refreshUsers();
            Inicio.f.txtusr.setText(result);
            result = Inicio.refreshRels();
            Inicio.f.txtrel.setText(result);
            JOptionPane.showMessageDialog(null, "Recuerde guardar para mantener los cambios en la memoria", "RECORDATORIO",JOptionPane.INFORMATION_MESSAGE);
            btnsave.setEnabled(true);
	}
    }//GEN-LAST:event_bttcargarActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String Lineas = "usuarios\r\n";
        Lineas += this.txtusr.getText();
        Lineas += "relaciones\r\n";
        Lineas += this.txtrel.getText();
        
        Boolean val = Inicio.WriteContent(Lineas, Inicio.appfile);
        if (val == true){
            JOptionPane.showMessageDialog(null, "Se ha guardado el contenido satisfactoriamente", "GUARDADO",JOptionPane.INFORMATION_MESSAGE);
            btnsave.setEnabled(false);
        }
        else
        { 
          JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "ERROR",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        // TODO add your handling code here:
        dlguser aguser = new dlguser(this, true);
        aguser.setVisible(true);
        if (aguser.val == true)
        {
            JOptionPane.showMessageDialog(null, "Recuerde guardar para mantener los cambios en la memoria", "RECORDATORIO", JOptionPane.INFORMATION_MESSAGE);
            this.btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_adduserActionPerformed

    private void addrelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrelActionPerformed
        // TODO add your handling code here:
        dlgrel agrel = new dlgrel(this, true);
        agrel.fillUser1();
        agrel.fillUser2();
        agrel.setVisible(true);
        if (agrel.val == true)
        {
            JOptionPane.showMessageDialog(null, "Recuerde guardar para mantener los cambios en la memoria", "RECORDATORIO", JOptionPane.INFORMATION_MESSAGE);
            this.btnsave.setEnabled(true);
        }  
    }//GEN-LAST:event_addrelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrel;
    private javax.swing.JButton adduser;
    private javax.swing.JButton bsalir;
    public javax.swing.JButton btnsave;
    private javax.swing.JButton bttcargar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblarchivosel;
    public javax.swing.JTextArea txtrel;
    public javax.swing.JTextArea txtusr;
    // End of variables declaration//GEN-END:variables
}
